-- Item location bitflags. 3.3.5 / Lua 5.1 supports native hex literals,
-- so the tonumber("0x...", 16) workaround from the 1.12 sibling is gone.
ITEM_INVENTORY_LOCATION_PLAYER		= 0x00100000;
ITEM_INVENTORY_LOCATION_BAGS		= 0x00200000;
ITEM_INVENTORY_LOCATION_BANK		= 0x00400000;
ITEM_INVENTORY_BAG_BIT_OFFSET 		= 8; -- Number of bits that the bag index in GetInventoryItemsForSlot gets shifted to the left.
ITEM_INVENTORY_BANK_BAG_OFFSET      = 4;

-- Inventory slots
INVSLOT_AMMO		= 0;
INVSLOT_HEAD 		= 1; INVSLOT_FIRST_EQUIPPED = INVSLOT_HEAD;
INVSLOT_NECK		= 2;
INVSLOT_SHOULDER	= 3;
INVSLOT_BODY		= 4;
INVSLOT_CHEST		= 5;
INVSLOT_WAIST		= 6;
INVSLOT_LEGS		= 7;
INVSLOT_FEET		= 8;
INVSLOT_WRIST		= 9;
INVSLOT_HAND		= 10;
INVSLOT_FINGER1		= 11;
INVSLOT_FINGER2		= 12;
INVSLOT_TRINKET1	= 13;
INVSLOT_TRINKET2	= 14;
INVSLOT_BACK		= 15;
INVSLOT_MAINHAND	= 16;
INVSLOT_OFFHAND		= 17;
INVSLOT_RANGED		= 18;
INVSLOT_TABARD		= 19;
INVSLOT_LAST_EQUIPPED = INVSLOT_TABARD;

INVSLOTS_EQUIPABLE_IN_COMBAT = {
[INVSLOT_MAINHAND] = true,
[INVSLOT_OFFHAND] = true,
[INVSLOT_RANGED] = true,
}

-- Item IDs
HEARTHSTONE_ITEM_ID = 6948;

--
-- Equipment Set
--
MAX_EQUIPMENT_SETS_PER_PLAYER = 10;
EQUIPMENT_SET_EMPTY_SLOT = 0;
EQUIPMENT_SET_IGNORED_SLOT = 1;
EQUIPMENT_SET_ITEM_MISSING = -1;

--
-- Totems
--

MAX_TOTEMS = 4;

FIRE_TOTEM_SLOT = 1;
EARTH_TOTEM_SLOT = 2;
WATER_TOTEM_SLOT = 3;
AIR_TOTEM_SLOT = 4;

STANDARD_TOTEM_PRIORITIES = {1, 2, 3, 4};

SHAMAN_TOTEM_PRIORITIES = {
	EARTH_TOTEM_SLOT,
	FIRE_TOTEM_SLOT,
	WATER_TOTEM_SLOT,
	AIR_TOTEM_SLOT,
};

-- Druid Forms.
CAT_FORM = 1;
BEAR_FORM = 5;

--
-- Item quality. 3.3.5 doesn't ship LE_ITEM_QUALITY_* constants (those
-- appeared in 4.x); the engine indexes ITEM_QUALITY_COLORS by raw
-- numeric quality 0..7. Define them here so consumers ported from
-- modern code keep working.
--
LE_ITEM_QUALITY_POOR      = 0;
LE_ITEM_QUALITY_COMMON    = 1;
LE_ITEM_QUALITY_UNCOMMON  = 2;
LE_ITEM_QUALITY_RARE      = 3;
LE_ITEM_QUALITY_EPIC      = 4;
LE_ITEM_QUALITY_LEGENDARY = 5;
LE_ITEM_QUALITY_ARTIFACT  = 6;
LE_ITEM_QUALITY_HEIRLOOM  = 7;

--
-- Class
--
CLASS_SORT_ORDER = {
	"WARRIOR",
	"DEATHKNIGHT",
	"PALADIN",
	"PRIEST",
	"SHAMAN",
	"DRUID",
	"ROGUE",
	"MAGE",
	"WARLOCK",
	"HUNTER",
};
MAX_CLASSES = #CLASS_SORT_ORDER;

LOCALIZED_CLASS_NAMES_MALE = LOCALIZED_CLASS_NAMES_MALE or {};
LOCALIZED_CLASS_NAMES_FEMALE = LOCALIZED_CLASS_NAMES_FEMALE or {};
FillLocalizedClassList(LOCALIZED_CLASS_NAMES_MALE, false);
FillLocalizedClassList(LOCALIZED_CLASS_NAMES_FEMALE, true);

--
-- Inventory
--
BAG_ITEM_QUALITY_COLORS =
{
	[LE_ITEM_QUALITY_COMMON] = COMMON_GRAY_COLOR,
	[LE_ITEM_QUALITY_UNCOMMON] = UNCOMMON_GREEN_COLOR,
	[LE_ITEM_QUALITY_RARE] = RARE_BLUE_COLOR,
	[LE_ITEM_QUALITY_EPIC] = EPIC_PURPLE_COLOR,
	[LE_ITEM_QUALITY_LEGENDARY] = LEGENDARY_ORANGE_COLOR,
	[LE_ITEM_QUALITY_ARTIFACT] = ARTIFACT_GOLD_COLOR,
};

-- faction
PLAYER_FACTION_COLORS =
{
	[0] = PLAYER_FACTION_COLOR_HORDE,
	[1] = PLAYER_FACTION_COLOR_ALLIANCE,
};

-- Quest / project flavor identifier. Wrath Classic's project id is the
-- closest match for 3.3.5a private servers.
WOW_PROJECT_MAINLINE = 1;
WOW_PROJECT_CLASSIC = 2;
WOW_PROJECT_BURNING_CRUSADE_CLASSIC = 5;
WOW_PROJECT_WRATH_CLASSIC = 11;
WOW_PROJECT_CATACLYSM_CLASSIC = 14;
WOW_PROJECT_MISTS_CLASSIC = 19;
WOW_PROJECT_ID = WOW_PROJECT_WRATH_CLASSIC;

--
-- Glyph. Inscription is the headline new Wrath profession, so glyphs
-- are first-class on 3.3.5 (unlike the 1.12 sibling where this is false).
--
INSCRIPTION_AVAILABLE = true;

-- PaperDollFrame.lua
EQUIPPED_FIRST = 1;
EQUIPPED_LAST = 19;

BASE_MOVEMENT_SPEED = 7;
