-- Item IDs
HEARTHSTONE_ITEM_ID = 6948;

--
-- Totems
--

STANDARD_TOTEM_PRIORITIES = {1, 2, 3, 4};

SHAMAN_TOTEM_PRIORITIES = {
	EARTH_TOTEM_SLOT,
	FIRE_TOTEM_SLOT,
	WATER_TOTEM_SLOT,
	AIR_TOTEM_SLOT,
};

-- Druid Forms.
CAT_FORM = 1;
BEAR_FORM = 5;

--
-- Item quality. 3.3.5 doesn't ship LE_ITEM_QUALITY_* constants (those
-- appeared in 4.x); the engine indexes ITEM_QUALITY_COLORS by raw
-- numeric quality 0..7. Define them here so consumers ported from
-- modern code keep working.
--
LE_ITEM_QUALITY_POOR      = 0;
LE_ITEM_QUALITY_COMMON    = 1;
LE_ITEM_QUALITY_UNCOMMON  = 2;
LE_ITEM_QUALITY_RARE      = 3;
LE_ITEM_QUALITY_EPIC      = 4;
LE_ITEM_QUALITY_LEGENDARY = 5;
LE_ITEM_QUALITY_ARTIFACT  = 6;
LE_ITEM_QUALITY_HEIRLOOM  = 7;

--
-- Inventory
--
BAG_ITEM_QUALITY_COLORS =
{
	[LE_ITEM_QUALITY_COMMON] = COMMON_GRAY_COLOR,
	[LE_ITEM_QUALITY_UNCOMMON] = UNCOMMON_GREEN_COLOR,
	[LE_ITEM_QUALITY_RARE] = RARE_BLUE_COLOR,
	[LE_ITEM_QUALITY_EPIC] = EPIC_PURPLE_COLOR,
	[LE_ITEM_QUALITY_LEGENDARY] = LEGENDARY_ORANGE_COLOR,
	[LE_ITEM_QUALITY_ARTIFACT] = ARTIFACT_GOLD_COLOR,
};

-- faction
PLAYER_FACTION_COLORS =
{
	[0] = PLAYER_FACTION_COLOR_HORDE,
	[1] = PLAYER_FACTION_COLOR_ALLIANCE,
};

-- Quest / project flavor identifier. Wrath Classic's project id is the
-- closest match for 3.3.5a private servers.
WOW_PROJECT_MAINLINE = 1;
WOW_PROJECT_CLASSIC = 2;
WOW_PROJECT_BURNING_CRUSADE_CLASSIC = 5;
WOW_PROJECT_WRATH_CLASSIC = 11;
WOW_PROJECT_CATACLYSM_CLASSIC = 14;
WOW_PROJECT_MISTS_CLASSIC = 19;
WOW_PROJECT_ID = WOW_PROJECT_WRATH_CLASSIC;

--
-- Glyph. Inscription is the headline new Wrath profession, so glyphs
-- are first-class on 3.3.5 (unlike the 1.12 sibling where this is false).
--
INSCRIPTION_AVAILABLE = true;

BASE_MOVEMENT_SPEED = 7;
